var data = [
  {
    'name': 'Aguaymanto',
    'name2': 'Restaurante Aguaymanto',
    'phrase': 'Buenos cócteles',
    'address': 'Av Horacio Urteaga 1500, Jesús María 15072',
    'phone': '(01) 7172302',
  },
  {
    'name': 'El Centolla',
    'name2': 'Panaderia Centolla',
    'phrase': 'Recomendable para ir con niños',
    'address': 'Av Arnaldo Marquez 1629, Jesús María 15072',
    'phone': '(01) 6366354',
  },
  {
    'name': 'El Aguajal',
    'name2': 'Restaurante El Aguajal',
    'phrase': 'comida selvática',
    'address': 'Jr. Huiracocha 1498 Jesús Maria, Cercado de Lima 15072',
    'phone': '(01) 4319758',
  },
  {
    'name': 'La Picante',
    'name2': 'Restaurante La Picante',
    'phrase': 'Ambiente relajado',
    'address': 'Av Húsares de Junín 651, Jesús María 15072',
    'phone': '(01) 2373689',
  },
  {
    'name': 'La Baguette',
    'name2': 'Panadería La Baguette',
    'phrase': 'Panadería',
    'address': 'Jirón Sanchez Cerro 2134, Jesús María 15072',
    'phone': '(01) 7155310',
  },
  {
    'name': 'La Cabañita',
    'name2': 'Restaurante La Cabañita',
    'phrase': 'Ambiente relajado',
    'address': 'Av. Salaverry, Jesús María 15072',
    'phone': '(01) 4657890',
  },
  {
    'name': 'Cevichería <br> Juancito',
    'name2': 'Cevichería Juancito',
    'phrase': 'Marisquería',
    'address': 'Jirón Huiracocha 1662, Jesús María 15072',
    'phone': '(01) 2613414',
  },
  {
    'name': 'La Cuchara <br> Brava',
    'name2': 'Restaurante La Cuchara Brava',
    'phrase': 'Buenos cócteles', 
    'address': 'Jirón Huiracocha 1833, Jesús María 15072',
    'phone': '(01) 5045285',
  },
  {
    'name': 'Mar & Fuego',
    'name2': 'Cevichería Mar & Fuego',
    'phrase': 'Buenos cócteles',
    'address': 'Av Horacio Urteaga 1498, Jesús María 15072',
    'phone': '(01) 4235619',
  },
];